# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Place.create(name: "★茅ヶ崎市")
Place.create(name: "厚木市")
Place.create(name: "綾瀬市")
Place.create(name: "伊勢原市")
Place.create(name: "海老名市")
Place.create(name: "小田原市")
Place.create(name: "鎌倉市")
Place.create(name: "川崎市")
Place.create(name: "相模原市")
Place.create(name: "座間市")
Place.create(name: "逗子市")
Place.create(name: "秦野市")
Place.create(name: "平塚市")
Place.create(name: "藤沢市")
Place.create(name: "三浦市")
Place.create(name: "南足柄市")
Place.create(name: "大和市")
Place.create(name: "横須賀市")
Place.create(name: "横浜市")
Place.create(name: "愛川町")
Place.create(name: "大井町")
Place.create(name: "大磯町")
Place.create(name: "開成町")
Place.create(name: "寒川町")
Place.create(name: "中井町")
Place.create(name: "二宮町")
Place.create(name: "箱根町")
Place.create(name: "葉山町")
Place.create(name: "松田町")
Place.create(name: "真鶴町")
Place.create(name: "山北町")
Place.create(name: "湯河原町")
Place.create(name: "清川町")